config/routes.rb
AlexMizzouScraper::Application.routes.draw do
  resources :addresses
  match "/scrape" => "addresses#scrape"

  

  root :to => 'addresses#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
  validates :encoded_address, :uniqueness => true

end

app/models/search_string.rb
class SearchString < ActiveRecord::Base
    require "net/http"
    def self.scrape_speeder_last_name
      url=URI.parse("http://www.missouri.edu/PF/pf.cgi")
      ("a".."z").each do |a|
        ("a".."z").each do |b|
          post_args = {"last_name" => a+b + "*"}
          resp, data = Net::HTTP.post_form(url, post_args)
          if resp.code == "200" && data.match("0 matches") != nil && data.match("30 matches found") == nil
            puts "blank last name set found...marking as done"
            SearchString.where(:last_name => a+b).each do |x|
              x.completed = 0
              x.save
            end
          end
        end
      end
            
    end
    def self.scrape_speeder_first_name
      url=URI.parse("http://www.missouri.edu/PF/pf.cgi")
      ("a".."z").each do |a|
        ("a".."z").each do |b|
          post_args = {"first_name" => a+b + "*"}
          resp, data = Net::HTTP.post_form(url, post_args)
          if resp.code == "200" && data.match("0 matches") != nil && data.match("30 matches found") == nil
            puts "blank last name set found...marking as done"
            SearchString.where(:first_name => a+b).each do |x|
              x.completed = 0
              x.save
            end
          end
        end
      end
            
    end      
          
    def self.scrape
      url=URI.parse("http://www.missouri.edu/PF/pf.cgi")
      SearchString.where(:completed => nil).limit(10000).each do |ss|
            
                post_args = {"first_name" => ss.first_name + "*", "last_name" => ss.last_name + "*"}
                puts post_args
                resp, data = Net::HTTP.post_form(url, post_args)
                puts resp
                if resp.code == "200"
                  if data.match("More than 30 matches found")
                    ss.completed = 99
                    ss.save
                  else
                    ss.completed=1
                    ss.save
                    puts "request completed"
                    parsed_data = SearchString.parse(data)
                    parsed_data.each do |x|
                      puts x
                      @address = Address.new({encoded_address: x[0], key: x[1]})
                      @address.save
                    end
                  end
                else
                  ss.completed = 404
                  ss.save
                end
          puts ss.first_name + "     " + ss.last_name
          puts Address.count
          end
    # redirect_to :action => "index"

  end
  def self.parse(x)
    done = false
    results = []
    temp_results = []
    while done != true
      temp = x.index("decrypt")
      if temp == nil
        done = true
      else
        temp2 = x.index(";", temp)
        r = x[temp..temp2]
        x = x[temp2..-1]
        temp_results << r[8..-4]
      end
    end  
    temp_results.each do |x|
      t = x.split(",")
      results << [t[0][1..-2], t[1][2..-2]]
    end
    return results  
  end
  


end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  require 'net/http'
  
  def scrape
    url=URI.parse("http://www.missouri.edu/PF/pf.cgi")
    SearchString.where(:completed => nil).each do |ss|
          begin
              post_args = {"first_name" => ss.first_name + "*", "last_name" => ss.last_name + "*"}
              resp, data = Net::HTTP.post_form(url, post_args)
              if resp.code == "200"
                if data.match("More than 30 matches found")
                  ss.completed = 99
                  ss.save
                else
                  ss.completed=1
                  parsed_data = parse(data)
                  parsed_data.each do |x|
                    @address = Address.new({encoded_address: x[0], key: x[1]})
                    @address.save
                  end
                end
              else
                ss.completed = 404
                ss.save
              end
            rescue
            end
        puts ss.first name + "     " + ss.last_name
        puts Address.count
        end
  redirect_to :action => "index"
  
end
  
  
  def parse(x)
    done = false
    results = []
    temp_results = []
    while done != true
      temp = x.index("decrypt")
      if temp == nil
        done = true
      else
        temp2 = x.index(";", temp)
        r = x[temp..temp2]
        x = x[temp2..-1]
        temp_results << r[8..-4]
      end
    end  
    temp_results.each do |x|
      t = x.split(",")
      results << [t[0][1..-2], t[1][2..-2]]
    end
    return results  
  end
  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @addresses }
    end
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
    @address = Address.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @address }
    end
  end

  # GET /addresses/new
  # GET /addresses/new.json
  def new
    @address = Address.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @address }
    end
  end

  # GET /addresses/1/edit
  def edit
    @address = Address.find(params[:id])
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(params[:address])

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render json: @address, status: :created, location: @address }
      else
        format.html { render action: "new" }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /addresses/1
  # PUT /addresses/1.json
  def update
    @address = Address.find(params[:id])

    respond_to do |format|
      if @address.update_attributes(params[:address])
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address = Address.find(params[:id])
    @address.destroy

    respond_to do |format|
      format.html { redirect_to addresses_url }
      format.json { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/_form.html.erb
<%= form_for(@address) do |f| %>
  <% if @address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% @address.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :encoded_address %><br />
    <%= f.text_field :encoded_address %>
  </div>
  <div class="field">
    <%= f.label :key %><br />
    <%= f.text_field :key %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing address</h1>

<%= render 'form' %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<h1>Listing addresses</h1>

<table>
  <tr>
    <th>Encoded address</th>
    <th>Key</th>
    <th>email</th>
    <th></th>
    <th></th>
  </tr>

<% @addresses.each do |address| %>
  <tr>
    <td><%= address.encoded_address %></td>
    <td><%= address.key %></td>
    <td>email= <script> 
	str = "<%= address.encoded_address %>";
	key = "<%= address.key %>";
	document.write(decrypt(str, key)); 
	</script></td>
	<td><%= link_to 'Show', address %></td>
    <td><%= link_to 'Edit', edit_address_path(address) %></td>
    <td><%= link_to 'Destroy', address, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<h1>New address</h1>

<%= render 'form' %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<% javascript_include_tag "decrypter"%>
<p id="notice"><%= notice %></p> 

<p>
  <b>Encoded address:</b>
  <%= @address.encoded_address %>
</p>

<p>
  <b>Key:</b>
  <%= @address.key %>
</p>

result = <script> 
str = "<%= @address.encoded_address %>".slice(6,-6);
key = "<%= @address.key %>".slice(6,-6);
document.write(decrypt(str, key)); 
</script>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlexMizzouScraper</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>